object Version {
    const val kotlinVersion = "1.4.10"
    const val appCompatVersion = "1.2.0"
    const val constraintLayoutVersion = "2.0.4"
    const val materialVersion = "1.2.1"
    const val coreVersion = "1.3.2"
    const val navigationVersion = "2.3.0"
    const val rxJavaVersion = "2.2.17"
    const val rxAndroidVersion = "2.1.1"
    const val rxRelayVersion = "2.1.1"
    const val rxbindingVersion = "2.0.0"
    const val coreTestVersion = "3.3.0"
    const val testJunitVersion = "1.1.2"
    const val junit = "4.13"
    const val koinVersion = "2.1.6"
    const val lifecycleVersion = "2.2.0"
    const val roomVersion = "2.2.5"
    const val retrofitVersion = "2.7.1"
    const val okhttpVersion = "4.3.1"
    const val locationServiceVersion = "17.1.0"
    const val authVersion = "18.1.0"
    const val baseClientLibraryVersion = "17.5.0"
    const val identityVersion = "17.0.0"
    const val coroutines = "1.4.0"
    const val coroutinesManager = "1.5.0-RC"
}